---
- name: Add a Longhorn repository
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io
    kubeconfig: /etc/rancher/k3s/k3s.yaml  # Указываем путь к kubeconfig
  become: true

- name: Install Longhorn chart
  kubernetes.core.helm:
    name: longhorn
    namespace: longhorn-system
    chart_ref: longhorn/longhorn
    state: present
    create_namespace: true  # Создать пространство имен, если оно не существует
    values: 
      # Добавьте любые необходимые значения конфигурации для Helm chart
      # Например:
      # persistence:
      #   storageClass: "default"
    kubeconfig: /etc/rancher/k3s/k3s.yaml  # Указываем путь к kubeconfig
  become: true
