---
- name: Add a Longhorn repository
  become: true
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io
    kubeconfig: /etc/rancher/k3s/k3s.yaml  # Указываем путь к kubeconfig

- name: Install Longhorn chart
  become: true
  kubernetes.core.helm:
    name: longhorn
    namespace: longhorn-system
    chart_ref: longhorn/longhorn
    state: present
    create_namespace: true  # Создать пространство имен, если оно не существует
    kubeconfig: /etc/rancher/k3s/k3s.yaml  # Указываем путь к kubeconfig

- name: Apply the Kubernetes manifest
  kubernetes.core.k8s:
    state: present
    src: "/root/k3s/ansible/roles/longhorn/files/storageClass.yml"
    kubeconfig: /etc/rancher/k3s/k3s.yaml  # Указываем путь к kubeconfig
