---
- name: Add a Jenking repository
  become: true
  kubernetes.core.helm_repository:
    name: jenkins  
    repo_url: https://charts.jenkins.io
    kubeconfig: /etc/rancher/k3s/k3s.yaml  # Указываем путь к kubeconfig

- name: Install Jenkins
  become: true
  kubernetes.core.helm:
    name: jenkins  
    namespace: jenkins
    chart_ref: jenkins/jenkins
    state: present
    create_namespace: true  # Создать пространство имен, если оно не существует
    kubeconfig: /etc/rancher/k3s/k3s.yaml  # Указываем путь к kubeconfig
    set_values:
      - value: storageClassName=longhorn
        value_type: string

- name: Apply ingress manifest
  kubernetes.core.k8s:
    namespace: jenkins
    state: present
    src: "/root/k3s/ansible/roles/jenkins/files/ingress.yaml"
    kubeconfig: /etc/rancher/k3s/k3s.yaml  # Указываем путь к kubeconfig