# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
    config.vm.define "master" do |master|
     master.vm.box = "bento/ubuntu-22.04"
     master.vm.hostname = "master"
     master.vm.network "private_network", ip: "192.168.56.15"
     master.vm.provider "virtualbox" do |vb|
      vb.cpus = 4
      vb.gui = false
      vb.memory = "4096"
     end  
    end
   config.vm.define "worker" do |worker|  
     worker.vm.box = "bento/ubuntu-22.04"
     worker.vm.hostname = "worker"
     worker.vm.network "private_network", ip: "192.168.56.16"
     worker.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.gui = false
      vb.memory = "1024"
     end
   end
   config.vm.define "worker2" do |worker2|
     worker2.vm.box = "bento/ubuntu-22.04"
     worker2.vm.hostname = "worker2"
     worker2.vm.network "private_network", ip: "192.168.56.17"
     worker2.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.gui = false
      vb.memory = "1024"
     end
   end
   config.vm.define "ansible" do |ansible|
    ansible.vm.box = "bento/ubuntu-22.04"
    ansible.vm.hostname = "ansible"
    ansible.vm.network "private_network", ip: "192.168.56.18"
    ansible.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.gui = false
      vb.memory = "1024"
     end
    end
  end
   