---
- name: Get K3S_TOKEN
  ansible.builtin.command: cat /var/lib/rancher/k3s/server/node-token
  register: k3s_token

- name: Get master node IP
  ansible.builtin.command: hostname -I | awk '{print $1}'
  register: master_ip
