---
- name: Check if K3s is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/k3s  
  register: k3s_installed
  become: true

- name: Download and install K3s
  ansible.builtin.shell: "curl -sfL https://get.k3s.io | sh -"
  when: not k3s_installed.stat.exists  
  become: true

- name: Get K3S_TOKEN
  ansible.builtin.command: cat /var/lib/rancher/k3s/server/node-token
  register: k3s_token
  become: true

- name: Check if helm is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/helm
  register: helm_installed
  become: true

- name: Install helm
  when: not helm_installed.stat.exists  
  ansible.builtin.apt:
    name: helm
    state: present

- name: Read kubeconfig file
  shell: cat /etc/rancher/k3s/k3s.yaml
  register: kubeconfig_content
  become: true

- name: Print kubeconfig content
  debug:
    msg: "The content of kubeconfig is:\n{{ kubeconfig_content.stdout }}"

