---

- name: Setup Docker on master
  hosts: all
  roles:
    - role: geerlingguy.docker
  become: true


- name: Setup K3s on master node
  hosts: master
  become: true
  roles:
    - role: k3s

- name: Get K3S_TOKEN and K3S_URL from master node
  hosts: master
  gather_facts: no
  become: true
  tasks:
    - include_role:
        name: k3s
        tasks_from: master

- name: Install K3s on worker nodes
  hosts: worker
  become: true
  tasks:
    - include_role:
        name: k3s
        tasks_from: workers

- name: Install helm longhorn
  hosts: master
  become: true
  roles:
    - role: longhorn
